/*
 * Tcl 9 compatibility shim for TclX math support.
 */

#include "tclExtdInt.h"

void
TclX_MathInit(Tcl_Interp *interp)
{
    Tcl_Eval(interp,
        "namespace eval ::tclx {}\n"
        "\n"
        "proc ::tclx::CheckDouble {x} {\n"
        "    if {![string is double -strict $x]} {\n"
        "        return -code error \"expected floating-point number but got \\\"$x\\\"\"\n"
        "    }\n"
        "    return [expr {double($x)}]\n"
        "}\n"
        "\n"
        "if {![llength [info commands ::max]]} {\n"
        "    proc ::max {args} {\n"
        "        if {[llength $args] < 1} {\n"
        "            return -code error {wrong # args: max num1 ?..numN?}\n"
        "        }\n"
        "        set bestOrig [lindex $args 0]\n"
        "        set bestVal [::tclx::CheckDouble $bestOrig]\n"
        "        foreach x [lrange $args 1 end] {\n"
        "            set v [::tclx::CheckDouble $x]\n"
        "            if {$v > $bestVal} {\n"
        "                set bestVal $v\n"
        "                set bestOrig $x\n"
        "            }\n"
        "        }\n"
        "        return $bestOrig\n"
        "    }\n"
        "}\n"
        "\n"
        "if {![llength [info commands ::min]]} {\n"
        "    proc ::min {args} {\n"
        "        if {[llength $args] < 1} {\n"
        "            return -code error {wrong # args: min num1 ?..numN?}\n"
        "        }\n"
        "        set bestOrig [lindex $args 0]\n"
        "        set bestVal [::tclx::CheckDouble $bestOrig]\n"
        "        foreach x [lrange $args 1 end] {\n"
        "            set v [::tclx::CheckDouble $x]\n"
        "            if {$v < $bestVal} {\n"
        "                set bestVal $v\n"
        "                set bestOrig $x\n"
        "            }\n"
        "        }\n"
        "        return $bestOrig\n"
        "    }\n"
        "}\n"
        "\n"
        "if {![llength [info commands ::random]]} {\n"
        "    proc ::random {args} {\n"
        "        set argc [llength $args]\n"
        "        if {$argc == 0 || $argc > 2} {\n"
        "            return -code error {wrong # args: random limit | seed ?seedval?}\n"
        "        }\n"
        "        set first [lindex $args 0]\n"
        "        if {$first eq {seed}} {\n"
        "            if {$argc == 1} {\n"
        "                expr {srand([clock microseconds])}\n"
        "                return {}\n"
        "            }\n"
        "            set seed [lindex $args 1]\n"
        "            if {![string is integer -strict $seed]} {\n"
        "                return -code error \"expected integer but got \\\"$seed\\\"\"\n"
        "            }\n"
        "            expr {srand($seed)}\n"
        "            return {}\n"
        "        }\n"
        "        if {$argc != 1} {\n"
        "            return -code error {wrong # args: random limit | seed ?seedval?}\n"
        "        }\n"
        "        if {![string is integer -strict $first]} {\n"
        "            return -code error \"expected integer but got \\\"$first\\\"\"\n"
        "        }\n"
        "        set limit $first\n"
        "        if {$limit <= 0} {\n"
        "            return -code error {range must be > 0 and <=}\n"
        "        }\n"
        "        return [expr {int(rand() * $limit)}]\n"
        "    }\n"
        "}\n"
        "\n"
        "namespace eval ::tcl::mathfunc {\n"
        "    if {![llength [info commands min]]} {\n"
        "        proc min {a b} {expr {$a < $b ? $a : $b}}\n"
        "    }\n"
        "    if {![llength [info commands max]]} {\n"
        "        proc max {a b} {expr {$a > $b ? $a : $b}}\n"
        "    }\n"
        "    if {![llength [info commands random]]} {\n"
        "        proc random {limit} {expr {int(rand() * $limit)}}\n"
        "    }\n"
        "}\n"
        "\n"
        "if {![llength [info commands ::case]]} {\n"
        "    proc ::case {value args} {\n"
        "        tailcall switch -- $value {*}$args\n"
        "    }\n"
        "}\n");
}
